[[language]]
name = "html"
formatter = { command = 'C:\Users\Student\AppData\Roaming\npm\', args = ["prettier", "--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'C:\Users\Student\AppData\Roaming\npm\', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'C:\Users\Student\AppData\Roaming\npm\', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'C:\Users\Student\AppData\Roaming\npm\', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
auto-format = true
formatter = { command = 'C:\Users\Student\AppData\Roaming\npm\prettier.cmd', args = ["--parser", "typescript"] }

[language-server.typescript-language-server]
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true }}

[[language]]
name = "tsx"
formatter = { command = 'C:\Users\Student\AppData\Roaming\npm\prettier.cmd', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'C:\Users\Student\AppData\Roaming\npm\', args = ["--parser", "typescript"] }
auto-format = true
