inherits = "night_owl"

#"comment" = { fg = "slate", modifiers = ["slow_blink", "italic"] }

"diagnostic.error" = {underline = { color = "apricot", style = "curl"}, modifiers = ["slow_blink", "bold"]}
"diagnostic.warning" = { underline = { color = "lightning", style = "curl"}, modifiers = ["slow_blink", "bold"]}
"diagnostic.hint" = { underline = { color = "#afdbcc", style = "curl"}, modifiers = ["slow_blink", "bold"]}
"diagnostic.info" = { underline = { color = "delta", style = "curl"}, modifiers = ["slow_blink", "bold"]}
#"ui.virtual.inlay-hint" = {fg = "#435d84"}

'type' = { fg = '#1e720d' }
#'variable' = { fg = '#36cf17', modifiers = ['fast-blink'] }
'variable.builtin' = { fg = '#30b715', modifiers = ['italic'] }

'warning' = { fg = 'peach', modifiers = ['dim'] }
'error' = { fg = 'red', modifiers = ['dim'] }
'info' = { fg = 'blue', modifiers = ['dim']}
'hint' = { fg = 'paleblue', modifiers = ['dim']}


[palette]
apricot = "#f47868"
lightning = "#ffcd1c"
delta = "#6F44F0"




