inherits = "night_owl"

#"comment" = { fg = "slate", modifiers = ["slow_blink", "italic"] }

"diagnostic.error" = {underline = { color = "apricot", style = "curl"}, modifiers = ["italic", "bold"]}
"diagnostic.warning" = { underline = { color = "lightning", style = "curl"}, modifiers = ["italic", "bold"]}
"diagnostic.hint" = { underline = { color = "#afdbcc", style = "curl"}, modifiers = ["italic", "bold"]}
"diagnostic.info" = { underline = { color = "delta", style = "curl"}, modifiers = ["italic", "bold"]}


"ui.virtual" = { fg = "faint-blue" }
'type' = { fg = '#1e720d' }
'variable.builtin' = { fg = '#30b715', modifiers = ['italic'] }

'warning' = { fg = 'peach', modifiers = ['dim'] }
'error' = { fg = 'red', modifiers = ['dim'] }
'info' = { fg = 'blue', modifiers = ['dim']}
'hint' = { fg = 'paleblue', modifiers = ['dim']}


[palette]
apricot = "#f47868"
lightning = "#ffcd1c"
delta = "#6F44F0"
faint-blue = "#154c79"

